### ISSUE TITLE
Feature Request : middleClick as command

### ISSUE THREAD

**Issue by emmgrr** [tumpio/mousecommander#1]
Some mice lack a middleButton.
E.g: some current Kensington Trackballs.
Plus in Linux it can be tricky to emulate this.

So the added command middleClick would fix this well.

Else the respective middleClickActions would also do it : 
1. open Link in new Tab
2. open Bookmark in new Tab

**Comment by tumpio** [comment]
That's not possible from Firefox extension. You could look up some program to emulate middle click on your OS.
