### ISSUE TITLE
No connection to native client application

### ISSUE THREAD

**Issue by AlexVSharp** [tumpio/mousecommander#2]
_edited_

The client can't run on the default Linux Mint 19.2 x64 (Ubuntu 18.04 LTS) installation as it was compiled with a newer version of Glibc (2.28) while the system comes preinstalled with version 2.27
 
[21277] Error loading Python lib '/opt/mousecommander/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/mousecommander/libpython3.6m.so.1.0)

**Comment by tumpio** [comment]
Hi @AlexVSharp 

I re-build it with Ubuntu 16.04 LTS. Please try if that works also for your:
https://github.com/tumpio/mousecommander/releases/download/v1.0.2/mousecommander-client-x86_64.deb

**Comment by AlexVSharp** [comment]
I tested it and it works now. Thanks.
