### ISSUE TITLE
Program runs two istances on browser start

### ISSUE THREAD

**Issue by AlexVSharp** [tumpio/mousecommander#3]
### Expected behavior
Launching the browser starts mousecommander.

### Actual behavior
Launching the browser sometimes runs two instances of mousecommander at the same time, which leads to commands not functioning properly (e.g. wheel changes tabs when it shouldn't; clicking anything closes tabs, etc). Restarting the browser, or pkilling both instances fixes the problem.

### Additional information
* Running Firefox 75 on Linux Mint 19.2 x64. The software version is for Ubuntu 16.04 LTS.
* The problem could be related to the "Multi-Account Containers" (github.com/mozilla/multi-account-containers) or "Simple Tab Groups" (github.com/drive4ik/simple-tab-groups) addons, since it doesn't occur all the time. I couldn't test with my current setup.

**Comment by tumpio** [comment]
Possibly fixed in 1.0.5 extension release.
